name: Automerge

on:
  schedule:
    - cron: '0 * * * *'
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

jobs:
  automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@46b8b95bac3325964476acc56f9160a98d1e7291
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          squash-title: true
          do-not-merge-labels: 'do not merge,awaiting maintainer feedback,awaiting user reply'
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: ${{ github.ref == 'refs/heads/debug-automerge' }}