name: Automerge

on:
  schedule:
    - cron: '* * * * *'
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

jobs:
  automerge:
    if: >
      startsWith(github.repository, 'gregxsunday/homebrew-rce-labs') &&
      (
        (
          github.event.review.state == 'approved' &&
          github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name
        ) || github.event_name != 'pull_request_review'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@46b8b95bac3325964476acc56f9160a98d1e7291
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          squash-title: true
          do-not-merge-labels: 'do not merge,awaiting maintainer feedback,awaiting user reply'
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: ${{ github.ref == 'refs/heads/debug-automerge' }}